export const CREATE_COMMENT_REQUEST='CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS='CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE='CREATE_COMMENT_FAILURE';


export const DELETE_COMMENT_REQUEST='DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS='DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE='DELETE_COMMENT_FAILURE';

export const FETCH_COMMENT_REQUEST='FETCH_COMMENT_REQUEST';
export const FETCH_COMMENT_SUCCESS='FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_FAILURE='FETCH_COMMENT_FAILURE';